syntax on
set number
set relativenumber
set backspace=indent,eol,start
filetype plugin indent on
set incsearch
set ignorecase
set smartcase
set hlsearch
set nowrap
set autoindent
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4
set titlestring=%t
set title
set ruler
set nobackup
set history=99
